# Generated by Django 3.1.4 on 2021-01-11 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TableTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableteam_created_by', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.manager')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableteam_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_created_by', to=settings.AUTH_USER_MODEL)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='fantasy.tableteam')),
                ('team10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team10', to='fantasy.tableteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='fantasy.tableteam')),
                ('team3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team3', to='fantasy.tableteam')),
                ('team4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team4', to='fantasy.tableteam')),
                ('team5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team5', to='fantasy.tableteam')),
                ('team6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team6', to='fantasy.tableteam')),
                ('team7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team7', to='fantasy.tableteam')),
                ('team8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team8', to='fantasy.tableteam')),
                ('team9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team9', to='fantasy.tableteam')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.table'),
        ),
    ]
