# Generated by Django 3.1.4 on 2021-01-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_auto_20210111_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableteam',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
