# Generated by Django 3.1.4 on 2021-01-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_auto_20210111_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='total_champion_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='total_draw_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='total_loss_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='total_point_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='total_runnerup_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='total_score_away_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='total_score_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='total_win_second',
            field=models.IntegerField(default=0),
        ),
    ]
