# Generated by Django 3.1.4 on 2021-01-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_auto_20210118_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
