# Generated by Django 3.1.4 on 2021-01-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_league_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('total_champion', models.IntegerField(default=0)),
                ('total_runnerup', models.IntegerField(default=0)),
                ('total_point', models.IntegerField(default=0)),
                ('total_win', models.IntegerField(default=0)),
                ('total_draw', models.IntegerField(default=0)),
                ('total_loss', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('total_score_away', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_champion',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_champion_second',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_draw',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_draw_second',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_loss',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_loss_second',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_point',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_point_second',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_runnerup',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_runnerup_second',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_score_away',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_score_away_second',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_score_second',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_win',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='total_win_second',
        ),
        migrations.AddField(
            model_name='manager',
            name='career',
            field=models.ManyToManyField(to='fantasy.Career'),
        ),
    ]
