# Generated by Django 3.1.4 on 2021-01-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0009_auto_20210125_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweek',
            name='matches',
            field=models.ManyToManyField(blank=True, null=True, to='fantasy.Match'),
        ),
        migrations.AlterField(
            model_name='league',
            name='gameweeks',
            field=models.ManyToManyField(blank=True, null=True, to='fantasy.Gameweek'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='career',
            field=models.ManyToManyField(blank=True, null=True, to='fantasy.Career'),
        ),
        migrations.AlterField(
            model_name='table',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='fantasy.TableTeam'),
        ),
    ]
