# Generated by Django 3.1.4 on 2021-01-28 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy', '0010_auto_20210125_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='League19Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('league1', models.IntegerField(default=0)),
                ('league2', models.IntegerField(default=0)),
                ('league3', models.IntegerField(default=0)),
                ('league4', models.IntegerField(default=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.manager')),
            ],
        ),
        migrations.CreateModel(
            name='League19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league19_created_by', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(to='fantasy.League19Team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league19_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win1', models.IntegerField(default=0)),
                ('win2', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='fantasy.manager')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='fantasy.manager')),
            ],
        ),
    ]
