# Generated by Django 3.1.4 on 2021-02-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_league_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='total_topscorer_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableteam',
            name='score_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableteam',
            name='topscorer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableteam',
            name='topscorer_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tableteam',
            name='vanga',
            field=models.IntegerField(default=0),
        ),
    ]
