# Generated by Django 3.1.4 on 2021-02-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0014_auto_20210208_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='total_match',
            field=models.IntegerField(default=0),
        ),
    ]
